eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  config:
    import: optional:configserver:http://localhost:9262
  application:
    name: auth-module
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/access
    username: root
    password:

# RabbitMQ settings
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 465
    username: chiorlujack@gmail.com
    password: hbclsxrhyowmcbwi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
